# Generated by Django 3.1.3 on 2020-11-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityCharts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
